version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: project3a_image
    container_name: project3a_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    